-- 创建饮食模块全局分类字典表
CREATE TABLE public.diet_categories (
    id bigint generated by default as identity primary key,
    module text not null check (module in ('foods', 'recipes', 'restaurants')),
    name text not null,
    sort_order integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- 同一个模块下不能出现同名分类
    CONSTRAINT unique_module_category_name UNIQUE(module, name)
);

-- 启用行级安全（RLS）保护
ALTER TABLE public.diet_categories ENABLE ROW LEVEL SECURITY;

-- 当前阶段：允许所有经身份验证的后台用户读写
CREATE POLICY "Enable read access for authenticated users to diet_categories" ON public.diet_categories FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable insert for authenticated users to diet_categories" ON public.diet_categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users to diet_categories" ON public.diet_categories FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users to diet_categories" ON public.diet_categories FOR DELETE USING (auth.role() = 'authenticated');
-- 公开前台：允许匿名/全体直接拉取字典过滤
CREATE POLICY "Enable read access for all users to diet_categories" ON public.diet_categories FOR SELECT USING (true);

-- 注入目前我们在各个页面写死的默认平滑过渡初始数据：
INSERT INTO public.diet_categories (module, name, sort_order) VALUES
('foods', '水果', 10),
('foods', '肉类', 20),
('foods', '蔬菜', 30),
('foods', '调味料', 40),
('foods', '其他', 99),

('recipes', '简餐', 10),
('recipes', '正餐', 20),
('recipes', '饮料', 30),
('recipes', '甜品', 40),
('recipes', '其他', 99),

('restaurants', '日料', 10),
('restaurants', '法餐', 20),
('restaurants', '火锅', 30),
('restaurants', '中餐', 40),
('restaurants', '西餐', 50),
('restaurants', '咖啡厅', 60),
('restaurants', '其他', 99);
